"""Replay reader over local SQLite replay state.

The v0.2 `oep replay <decision_id>` subcommand is a thin reader over the
existing demo SQLite replay store. It does not introduce new persistence,
live model calls, or service dependencies; it reconstructs the recorded
permission trace by joining rows already written by the deterministic
demo runner.
"""

# ruff: noqa: F401

import os
import shutil
import signal
import sqlite3
import subprocess

from oep_permissions.replay.opa import (
    MIN_OPA_EVAL_TIMEOUT_SECONDS,
    OEP_OPA_EVAL_TIMEOUT_SECONDS_ENV,
    OPA_BATCH_DECISION_QUERY,
    OPA_DECISION_QUERY_PATH,
    OPA_ERROR_OUTPUT_LIMIT,
    OPA_EVAL_TIMEOUT_SECONDS,
    OPA_STDIN_INPUT_LIMIT_BYTES,
    _bounded_opa_error_output,
    _evaluate_opa_decisions,
    _format_timeout_seconds,
    _kill_opa_process,
    _opa_eval_timeout_seconds,
    _policy_input_from_record,
    _reap_opa_process,
    _require_opa_stdin_within_limit,
    _require_positive_timeout_seconds,
    _run_opa_eval,
    _terminate_opa_process,
    _timeout_validation_message,
)
from oep_permissions.replay.records import (
    COUNTERFACTUAL_CLAIM_BOUNDARY,
    V03_COUNTERFACTUAL_CLAIM_BOUNDARY,
    CounterfactualReplayRecord,
    JoinInconsistencyError,
    OpaEvaluationError,
    ReplayError,
    ReplayRecord,
    SchemaValidationError,
    StateNotFoundError,
    _decision_label,
    _freeze_json_object,
    _freeze_json_value,
    _loads_object,
    _matched_rules,
    _non_negative_number,
    _optional_string,
    _ReplayPayloadCache,
    _require_object,
    _require_string,
    _stable_number,
    _string_list,
    _thaw_json_object,
    _thaw_json_value,
    _utc_now,
    _validate_counterfactual_replay,
    _validate_permission_packet,
)
from oep_permissions.replay.storage import (
    DEFAULT_SQLITE_BATCH_VARIABLE_LIMIT,
    MAX_SQLITE_BATCH_VARIABLE_LIMIT,
    OEP_SQLITE_BATCH_VARIABLE_LIMIT_ENV,
    SQLITE_BATCH_PLACEHOLDER_BASE_BUCKETS,
    SQLITE_REPLAY_BUSY_TIMEOUT_SECONDS,
    _cached_manifest_summary,
    _cached_trace_payload,
    _connect_read_only_state,
    _decision_id_placeholder_bucket,
    _decision_id_placeholders,
    _manifest_summary,
    _padded_decision_id_parameters,
    _raise_missing_decision,
    _reconstruct_decision_from_row,
    _reconstruct_decisions_from_connection,
    _require_join_consistency,
    _select_decision_rows,
    _sqlite_batch_placeholder_buckets,
    _sqlite_batch_variable_limit,
    _sqlite_read_only_uri,
    reconstruct_decision,
    reconstruct_decisions,
)
from oep_permissions.replay.surfaces import (
    DETERMINISTIC_SURFACES,
    EVALUATIVE_SURFACES,
    SURFACE_FIELD_BY_NAME,
    SURFACE_NAMES,
    _apply_budget_denial,
    _base_counterfactual_output,
    _budget_cap_from_policy,
    _budget_delta_from_policy,
    _cache_delta_from_policy,
    _counterfactual_policy_version,
    _counterfactual_record_from_parts,
    _decision_diff,
    _decision_metadata,
    _model_delta_from_substitution,
    _nd_builtin_cache_entry_count,
    _normalize_substitutions,
    _normalize_surface_names,
    _parse_model_substitution,
    _recorded_step_cost_usd,
    _snapshot_from_opa_decision,
    _snapshot_from_record,
    _substituted_policy_path,
    _substitution_effective_version,
    _surface_attribution_confidence,
    _surface_change,
    _surface_change_class,
    _surface_delta_for_substitutions,
    _surface_diff_row,
    _surface_effective_version,
    _validate_replay_timestamp_utc,
    counterfactual_replay_decision,
    counterfactual_replay_decisions,
    decision_surface_presence,
    diff_decision_surfaces,
    project_pre_session_cost,
    replay_decision_with_substitutions,
    simulate_reserve_commit_release,
)
from oep_permissions.replay.wrapper import (
    ALLOWED_OPA_COMMAND_WRAPPER_OPTIONS,
    ALLOWED_OPA_COMMAND_WRAPPERS,
    OEP_OPA_COMMAND_WRAPPER_ENV,
    OPA_DOCKER_IMAGE_RE,
    OPA_DOCKER_MEMORY_VALUE_RE,
    OPA_WRAPPER_NUMERIC_VALUE_RE,
    OPA_WRAPPER_OPTIONS_WITH_VALUES,
    OPA_WRAPPER_USER_VALUE_RE,
    TRUSTED_OPA_WRAPPER_DIRS,
    WINDOWS_SYSTEM_ROOT_ENV_NAMES,
    WINDOWS_SYSTEM_ROOT_FALLBACK,
    WINDOWS_TRUSTED_OPA_WRAPPER_ROOT_ENV_NAMES,
    _docker_read_only_volume_mapping,
    _docker_read_only_volume_mappings,
    _is_absolute_host_volume_source,
    _is_absolute_opa_wrapper_search_path_entry,
    _opa_command,
    _opa_command_wrapper_search_path,
    _opa_policy_bundle_data_path,
    _raise_unauthorized_opa_wrapper_argument,
    _resolve_opa_command_wrapper_executable,
    _resolve_windows_filesystem_path,
    _resolve_windows_opa_command_wrapper_path,
    _split_wrapper_option,
    _trusted_windows_opa_wrapper_roots,
    _validate_docker_opa_command_wrapper,
    _validate_docker_read_only_volume,
    _validate_docker_wrapper_option_value,
    _validate_opa_command_wrapper,
    _validate_opa_wrapper_option_value,
    _validate_option_only_opa_command_wrapper,
    _windows_path_is_relative_to,
)

__all__ = [
    "CounterfactualReplayRecord",
    "JoinInconsistencyError",
    "OEP_OPA_COMMAND_WRAPPER_ENV",
    "OEP_OPA_EVAL_TIMEOUT_SECONDS_ENV",
    "OEP_SQLITE_BATCH_VARIABLE_LIMIT_ENV",
    "OPA_STDIN_INPUT_LIMIT_BYTES",
    "OPA_EVAL_TIMEOUT_SECONDS",
    "OpaEvaluationError",
    "ReplayError",
    "ReplayRecord",
    "SchemaValidationError",
    "StateNotFoundError",
    "counterfactual_replay_decision",
    "counterfactual_replay_decisions",
    "decision_surface_presence",
    "diff_decision_surfaces",
    "project_pre_session_cost",
    "reconstruct_decisions",
    "reconstruct_decision",
    "replay_decision_with_substitutions",
    "simulate_reserve_commit_release",
]
